baseURL = "https://noellefavre.ch/"
languageCode = "fr-ch"
title = "Noëlle Favre - Médiation"
theme = "nf"

MetaDataFormat = "yaml"
DefaultContentLanguage = "fr"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

